# Generated by Django 2.1.15 on 2023-09-12 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('PetBPM', models.IntegerField()),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Steps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('PetID', models.AutoField(primary_key=True, serialize=False)),
                ('PetType', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], max_length=50)),
                ('PetBreed', models.CharField(max_length=100)),
                ('Policy', models.TextField()),
                ('PolicyStartDate', models.DateField()),
                ('PolicyEndDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ProductType', models.CharField(choices=[('FOOD', 'Pet Food'), ('ACCESSORY', 'Accessory'), ('TOY', 'Toy')], max_length=50)),
                ('Stock', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pethealth',
            name='PetID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='myapp.PetInfo'),
        ),
    ]
